name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests in'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - electron
      folder:
        description: 'Test folder to run (smoke or experiments)'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - experiments
      file:
        description: 'Specific test file to run (e.g., header1.smoke.cy.js). Leave empty to run all tests'
        required: false
        type: string
      email:
        description: 'Email address for failure notifications'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Cypress Test
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          browser: ${{ inputs.browser }}
          spec: ${{ inputs.file != '' && format('cypress/e2e/{0}/{1}', inputs.folder, inputs.file) || format('cypress/e2e/{0}/**/*.cy.js', inputs.folder) }}
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-${{ inputs.folder }}-results
          path: |
            cypress/videos/
            cypress/screenshots/
          retention-days: 30

      - name: Send Email on Failure
        if: ${{ inputs.email != '' && steps.cypress.outcome == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "❌ Cypress Tests Failed - ${{ inputs.folder }} folder"
          to: ${{ inputs.email }}
          from: GitHub Actions
          body: |
            Cypress tests have failed in the ${{ inputs.folder }} folder.
            
            Test Details:
            - Browser: ${{ inputs.browser }}
            - Folder: ${{ inputs.folder }}
            - File: ${{ inputs.file || 'All files' }}
            
            Check the GitHub Actions run for more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Videos and screenshots of the failed tests are available in the artifacts section of the run.
