name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests in'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - electron
      folder:
        description: 'Test folder to run (smoke or experiments)'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - experiments

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Cypress Test
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          browser: ${{ inputs.browser }}
          spec: cypress/e2e/${{ inputs.folder }}/**/*.cy.js

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-${{ inputs.folder }}-results
          path: |
            cypress/videos/
            cypress/screenshots/
          retention-days: 30
